// 오늘장부 블로그 전용 키워드 (자영업 주제만)
// category 는 blog/index.html 의 카테고리 탭과 정확히 일치해야 함:
//   매출관리 · 부가세/세금 · 절세꿀팁 · 배달앱 · 카드수수료 · 사업자등록 · 직원관리
// 섹션당 20개 (하루 1편/섹션이면 같은 주제는 20일마다 순환)
export const keywords = [
  // ── 매출관리 ──
  { keyword: '카페 일매출 관리하는 법', category: '매출관리', imageQuery: 'cafe coffee owner' },
  { keyword: '음식점 매출 관리 엑셀 vs 앱', category: '매출관리', imageQuery: 'restaurant owner laptop' },
  { keyword: '소상공인 매출 장부 정리법', category: '매출관리', imageQuery: 'small business bookkeeping' },
  { keyword: '편의점 일매출 기록 꿀팁', category: '매출관리', imageQuery: 'convenience store counter' },
  { keyword: '매출 데이터로 비수기 대비하는 법', category: '매출관리', imageQuery: 'sales chart analysis' },
  { keyword: '현금매출 누락 없이 기록하는 법', category: '매출관리', imageQuery: 'cash register money' },
  { keyword: '포스(POS) 매출과 장부 맞추기', category: '매출관리', imageQuery: 'pos terminal store' },
  { keyword: '월 매출 목표 세우고 관리하기', category: '매출관리', imageQuery: 'business goal planning' },
  { keyword: '매출 급감 원인 찾는 법', category: '매출관리', imageQuery: 'declining graph chart' },
  { keyword: '단골 매출 분석으로 재방문 늘리기', category: '매출관리', imageQuery: 'loyal customer cafe' },
  { keyword: '요일별 매출 패턴 활용하기', category: '매출관리', imageQuery: 'weekly calendar planning' },
  { keyword: '객단가 높이는 매출 관리', category: '매출관리', imageQuery: 'receipt money spend' },
  { keyword: '배달·홀 매출 따로 관리하기', category: '매출관리', imageQuery: 'restaurant counter delivery' },
  { keyword: '매출 기록 습관 만드는 법', category: '매출관리', imageQuery: 'daily notebook routine' },
  { keyword: '성수기 매출 극대화 전략', category: '매출관리', imageQuery: 'busy restaurant crowd' },
  { keyword: '매출 보고서 간단히 만드는 법', category: '매출관리', imageQuery: 'business report chart' },
  { keyword: '다점포 매출 한눈에 관리', category: '매출관리', imageQuery: 'multiple stores owner' },
  { keyword: '키오스크 매출 데이터 활용', category: '매출관리', imageQuery: 'kiosk self order' },
  { keyword: '계절 메뉴 매출 관리', category: '매출관리', imageQuery: 'seasonal menu cafe' },
  { keyword: '매출과 순이익 헷갈리지 않기', category: '매출관리', imageQuery: 'profit calculation money' },

  // ── 부가세/세금 ──
  { keyword: '자영업자 부가세 신고 방법', category: '부가세/세금', imageQuery: 'tax document calculator' },
  { keyword: '간이과세자 일반과세자 차이', category: '부가세/세금', imageQuery: 'tax paperwork desk' },
  { keyword: '부가세 신고 마감일 총정리', category: '부가세/세금', imageQuery: 'calendar deadline office' },
  { keyword: '자영업자 종합소득세 신고법', category: '부가세/세금', imageQuery: 'income tax form' },
  { keyword: '부가세 예정신고 대상과 방법', category: '부가세/세금', imageQuery: 'tax filing laptop' },
  { keyword: '매입세액 공제 받는 법', category: '부가세/세금', imageQuery: 'invoice receipt tax' },
  { keyword: '부가세 가산세 피하는 법', category: '부가세/세금', imageQuery: 'tax penalty document' },
  { keyword: '홈택스 부가세 신고 따라하기', category: '부가세/세금', imageQuery: 'computer screen office' },
  { keyword: '면세사업자 vs 과세사업자', category: '부가세/세금', imageQuery: 'tax exemption document' },
  { keyword: '부가세 환급 받는 경우', category: '부가세/세금', imageQuery: 'tax refund money' },
  { keyword: '세금계산서 발행 방법', category: '부가세/세금', imageQuery: 'electronic invoice laptop' },
  { keyword: '현금영수증 의무발행 업종', category: '부가세/세금', imageQuery: 'cash receipt store' },
  { keyword: '종합소득세 경비 인정 항목', category: '부가세/세금', imageQuery: 'expense receipt accounting' },
  { keyword: '사업자 세금 종류 총정리', category: '부가세/세금', imageQuery: 'tax documents folder' },
  { keyword: '초보 사장님 세금 달력', category: '부가세/세금', imageQuery: 'tax calendar planner' },
  { keyword: '부가세 신고 필요 서류', category: '부가세/세금', imageQuery: 'documents folder desk' },
  { keyword: '폐업 시 세금 정리', category: '부가세/세금', imageQuery: 'closing business paperwork' },
  { keyword: '세무대리 맡길까 직접할까', category: '부가세/세금', imageQuery: 'accountant meeting desk' },
  { keyword: '부가세 절세 합법 방법', category: '부가세/세금', imageQuery: 'saving tax coins' },
  { keyword: '카드매출 현금매출 세금 차이', category: '부가세/세금', imageQuery: 'card cash payment' },

  // ── 절세꿀팁 ──
  { keyword: '소상공인 절세 방법 총정리', category: '절세꿀팁', imageQuery: 'saving money coins' },
  { keyword: '자영업자 경비 처리 꿀팁', category: '절세꿀팁', imageQuery: 'receipt expense accounting' },
  { keyword: '매입세액 공제 제대로 받는 법', category: '절세꿀팁', imageQuery: 'invoice tax deduction' },
  { keyword: '사업용 신용카드 절세 활용', category: '절세꿀팁', imageQuery: 'business credit card' },
  { keyword: '노란우산공제 절세 효과', category: '절세꿀팁', imageQuery: 'savings safe money' },
  { keyword: '인건비 비용처리로 절세', category: '절세꿀팁', imageQuery: 'payroll salary document' },
  { keyword: '차량 유지비 경비 처리', category: '절세꿀팁', imageQuery: 'car business expense' },
  { keyword: '접대비 한도와 절세', category: '절세꿀팁', imageQuery: 'business dinner receipt' },
  { keyword: '감가상각으로 세금 줄이기', category: '절세꿀팁', imageQuery: 'equipment depreciation' },
  { keyword: '세액공제 vs 소득공제 차이', category: '절세꿀팁', imageQuery: 'tax form calculator' },
  { keyword: '소상공인 정책자금 활용', category: '절세꿀팁', imageQuery: 'government support money' },
  { keyword: '절세를 위한 영수증 관리', category: '절세꿀팁', imageQuery: 'receipts organizing box' },
  { keyword: '가족 직원 인건비 절세', category: '절세꿀팁', imageQuery: 'family business staff' },
  { keyword: '임차료 부가세 공제', category: '절세꿀팁', imageQuery: 'rent contract document' },
  { keyword: '연금저축 세액공제 자영업자', category: '절세꿀팁', imageQuery: 'pension savings plan' },
  { keyword: '기부금 세액공제 활용', category: '절세꿀팁', imageQuery: 'donation receipt hand' },
  { keyword: '소득공제 챙기는 꿀팁', category: '절세꿀팁', imageQuery: 'tax saving checklist' },
  { keyword: '중소기업 세액감면 대상', category: '절세꿀팁', imageQuery: 'small business tax' },
  { keyword: '절세 위해 미리 준비할 것', category: '절세꿀팁', imageQuery: 'financial planning desk' },
  { keyword: '자주 놓치는 절세 항목', category: '절세꿀팁', imageQuery: 'magnifying glass documents' },

  // ── 배달앱 ──
  { keyword: '배달앱 수수료 절약 방법', category: '배달앱', imageQuery: 'food delivery rider' },
  { keyword: '배민 쿠팡이츠 정산 이해하기', category: '배달앱', imageQuery: 'delivery food packaging' },
  { keyword: '배달 매출 부가세 처리법', category: '배달앱', imageQuery: 'delivery business owner' },
  { keyword: '배달앱 매출 누락 방지하는 법', category: '배달앱', imageQuery: 'smartphone food order' },
  { keyword: '배달앱 수수료 구조 완전정리', category: '배달앱', imageQuery: 'delivery app phone' },
  { keyword: '자체배달 vs 배달대행 비교', category: '배달앱', imageQuery: 'delivery motorcycle city' },
  { keyword: '배달 리뷰 관리로 매출 늘리기', category: '배달앱', imageQuery: 'phone review rating' },
  { keyword: '배달앱 광고 효과 있을까', category: '배달앱', imageQuery: 'online marketing ad' },
  { keyword: '배달 포장비 책정하는 법', category: '배달앱', imageQuery: 'food takeout box' },
  { keyword: '단건배달 수익성 분석', category: '배달앱', imageQuery: 'delivery single order' },
  { keyword: '배달 전용 메뉴 구성 전략', category: '배달앱', imageQuery: 'food menu design' },
  { keyword: '배달앱 정산 주기와 입금', category: '배달앱', imageQuery: 'bank deposit money' },
  { keyword: '배달 매출 세금 신고 주의점', category: '배달앱', imageQuery: 'tax delivery document' },
  { keyword: '배달 손익분기점 계산', category: '배달앱', imageQuery: 'calculator profit break' },
  { keyword: '우천·성수기 배달 매출', category: '배달앱', imageQuery: 'rainy day delivery' },
  { keyword: '쿠팡이츠 vs 배민 선택 기준', category: '배달앱', imageQuery: 'food delivery comparison' },
  { keyword: '배달 고객 재주문 유도법', category: '배달앱', imageQuery: 'happy customer food' },
  { keyword: '배달비 인상 고객 반응 관리', category: '배달앱', imageQuery: 'price notice sign' },
  { keyword: '배달앱 입점 절차와 비용', category: '배달앱', imageQuery: 'store registration online' },
  { keyword: '배달 매출 데이터 분석', category: '배달앱', imageQuery: 'delivery data chart' },

  // ── 카드수수료 ──
  { keyword: '카드 수수료 우대 신청 방법', category: '카드수수료', imageQuery: 'payment card terminal' },
  { keyword: '영세 중소가맹점 수수료율 정리', category: '카드수수료', imageQuery: 'card machine shop' },
  { keyword: '카드 매출 정산 주기 이해하기', category: '카드수수료', imageQuery: 'card payment store' },
  { keyword: '카드수수료 절감 현실 전략', category: '카드수수료', imageQuery: 'cash register payment' },
  { keyword: '우대수수료 대상 매출 기준', category: '카드수수료', imageQuery: 'small shop card reader' },
  { keyword: '카드 수수료 돌려받는 법', category: '카드수수료', imageQuery: 'money refund card' },
  { keyword: '간편결제 수수료 비교', category: '카드수수료', imageQuery: 'mobile pay phone' },
  { keyword: '제로페이 수수료 혜택', category: '카드수수료', imageQuery: 'qr code payment' },
  { keyword: '카드 단말기 종류와 비용', category: '카드수수료', imageQuery: 'card terminal device' },
  { keyword: '정기결제 구독 수수료', category: '카드수수료', imageQuery: 'subscription payment card' },
  { keyword: '카드사별 정산일 정리', category: '카드수수료', imageQuery: 'calendar bank finance' },
  { keyword: '신용카드 매출세액공제 받기', category: '카드수수료', imageQuery: 'card tax deduction' },
  { keyword: '부가세 신용카드 공제 한도', category: '카드수수료', imageQuery: 'tax card limit' },
  { keyword: '카드 수수료 회계처리', category: '카드수수료', imageQuery: 'accounting card fee' },
  { keyword: '배달앱 결제 수수료까지 합산', category: '카드수수료', imageQuery: 'delivery payment fee' },
  { keyword: '카드 매출 누락 시 불이익', category: '카드수수료', imageQuery: 'warning tax card' },
  { keyword: '현금 유도 할인의 함정', category: '카드수수료', imageQuery: 'cash discount sign' },
  { keyword: '수수료 낮은 결제수단 안내', category: '카드수수료', imageQuery: 'payment options store' },
  { keyword: '카드 매출 vs 현금 매출 비중', category: '카드수수료', imageQuery: 'cash card balance' },
  { keyword: '연 매출별 카드 수수료율', category: '카드수수료', imageQuery: 'revenue chart card' },

  // ── 사업자등록 ──
  { keyword: '사업자등록 절차 한눈에 정리', category: '사업자등록', imageQuery: 'business registration documents' },
  { keyword: '간이과세 일반과세 선택 기준', category: '사업자등록', imageQuery: 'choosing business form' },
  { keyword: '업종코드 정하는 법 자영업', category: '사업자등록', imageQuery: 'office paperwork checklist' },
  { keyword: '공동사업자 등록 주의사항', category: '사업자등록', imageQuery: 'business partners meeting' },
  { keyword: '온라인 사업자등록 따라하기', category: '사업자등록', imageQuery: 'laptop registration form' },
  { keyword: '사업자등록 필요 서류', category: '사업자등록', imageQuery: 'documents folder desk' },
  { keyword: '통신판매업 신고 방법', category: '사업자등록', imageQuery: 'online store laptop' },
  { keyword: '사업장 임대차계약 주의점', category: '사업자등록', imageQuery: 'lease contract signing' },
  { keyword: '개인사업자 vs 법인 차이', category: '사업자등록', imageQuery: 'business meeting decision' },
  { keyword: '부업도 사업자등록 해야 하나', category: '사업자등록', imageQuery: 'side job laptop' },
  { keyword: '휴업·폐업 신고 방법', category: '사업자등록', imageQuery: 'closed store sign' },
  { keyword: '사업자 통장·카드 만들기', category: '사업자등록', imageQuery: 'bank account business' },
  { keyword: '프랜차이즈 창업 등록 절차', category: '사업자등록', imageQuery: 'franchise store front' },
  { keyword: '사업자등록 후 첫 할 일', category: '사업자등록', imageQuery: 'checklist new business' },
  { keyword: '무등록 영업의 위험', category: '사업자등록', imageQuery: 'warning legal document' },
  { keyword: '업태·종목 정하는 법', category: '사업자등록', imageQuery: 'business category form' },
  { keyword: '인허가 필요 업종 정리', category: '사업자등록', imageQuery: 'permit license document' },
  { keyword: '사업자등록증 재발급 방법', category: '사업자등록', imageQuery: 'certificate document desk' },
  { keyword: '집 주소로 사업자등록 가능?', category: '사업자등록', imageQuery: 'home office desk' },
  { keyword: '사업자 단위 과세 제도', category: '사업자등록', imageQuery: 'multiple store tax' },

  // ── 직원관리 ──
  { keyword: '알바 4대보험 가입 기준', category: '직원관리', imageQuery: 'part time worker store' },
  { keyword: '주휴수당 계산법 자영업자', category: '직원관리', imageQuery: 'work schedule calendar' },
  { keyword: '알바 연차 수당 계산 방법', category: '직원관리', imageQuery: 'employee shop staff' },
  { keyword: '직원 급여 신고 방법 소상공인', category: '직원관리', imageQuery: 'payroll salary document' },
  { keyword: '2026 최저임금과 인건비', category: '직원관리', imageQuery: 'minimum wage money' },
  { keyword: '근로계약서 작성법', category: '직원관리', imageQuery: 'employment contract signing' },
  { keyword: '수습기간 급여와 규정', category: '직원관리', imageQuery: 'new employee training' },
  { keyword: '알바 해고·권고사직 주의점', category: '직원관리', imageQuery: 'workplace conversation' },
  { keyword: '4대보험 사업주 부담금', category: '직원관리', imageQuery: 'insurance cost calculator' },
  { keyword: '주 15시간 미만 알바 규정', category: '직원관리', imageQuery: 'part time schedule' },
  { keyword: '퇴직금 지급 기준과 계산', category: '직원관리', imageQuery: 'retirement money envelope' },
  { keyword: '직원 무단결근 대처법', category: '직원관리', imageQuery: 'empty shift schedule' },
  { keyword: '가족 직원 고용 시 주의', category: '직원관리', imageQuery: 'family business shop' },
  { keyword: '외국인 알바 고용 절차', category: '직원관리', imageQuery: 'diverse staff store' },
  { keyword: '야간·휴일 수당 계산', category: '직원관리', imageQuery: 'night shift work' },
  { keyword: '인건비 비용처리와 절세', category: '직원관리', imageQuery: 'payroll accounting tax' },
  { keyword: '5인 미만 사업장 노동법', category: '직원관리', imageQuery: 'small team workplace' },
  { keyword: '알바 채용 공고 잘 쓰는 법', category: '직원관리', imageQuery: 'hiring sign window' },
  { keyword: '직원 동기부여 현실 방법', category: '직원관리', imageQuery: 'happy team staff' },
  { keyword: '근로시간 관리와 기록', category: '직원관리', imageQuery: 'time clock work' },
]
